# backend/bootstrap.py

# Import standard modules
import logging
import os
# Import backend modules
from backend.db.db import init_db
import backend.db.users
import backend.db.hosts
import backend.db.aliases
# Import Settings & Logging
from settings.settings import settings
from log.log import setup_logging, get_logger

# ------------------------------------------------------------------------------
# Welcome log
# ------------------------------------------------------------------------------
def print_welcome(logger):
    masked_secret = "****" if settings.SECRET_KEY else "undefined"
    masked_admin_pwd = "****" if settings.ADMIN_PASSWORD else "undefined"
    masked_admin_hash = "****" if settings.ADMIN_PASSWORD_HASH else "undefined"

    logger.info(
        "%s starting | app_version=%s",
        settings.APP_NAME, settings.APP_VERSION
    )
    logger.info(
        "App settings: frontend=%s | host=%s | port=%d | secret=%s",
        settings.FRONTEND_DIR, settings.HTTP_HOST, settings.HTTP_PORT, masked_secret
    )
    logger.info(
        "Database: file=%s | reset=%s",
        settings.DB_FILE, settings.DB_RESET
    )
    logger.info(
        "Log: level=%s, to_file=%s, file=%s",
        settings.LOG_LEVEL, settings.LOG_TO_FILE, settings.LOG_FILE
    )
    logger.info(
        "Users: admin=%s | password=%s | hash=%s | hash_file=%s",
        settings.ADMIN_USER, masked_admin_pwd, masked_admin_hash, settings.ADMIN_PASSWORD_HASH_FILE
    )
    logger.info(
        "DNS: host file=%s | alias file=%s | reverse file=%s",
        settings.DNS_HOST_FILE, settings.DNS_ALIAS_FILE, settings.DNS_REVERSE_FILE
    )
    logger.info(
        "DHCP: ipv4 host file=%s | ipv4 leases file=%s | ipv6 host file=%s | ipv6 leases file=%s",
        settings.DHCP4_HOST_FILE, settings.DHCP4_LEASES_FILE, settings.DHCP6_HOST_FILE, settings.DHCP6_LEASES_FILE
    )

# ------------------------------------------------------------------------------
# Shutdown log
# ------------------------------------------------------------------------------
def print_goodbye(logger):
    logger.info(
        "Application %s shutting down | app_version=%s",
        settings.APP_NAME, settings.APP_VERSION
    )

# ================================
# Create DB if needed
# ================================
def docker_create_db(logger):
    # Reset database if requested
    if settings.DB_RESET and os.path.exists(settings.DB_FILE):
        logger.info("Removing existing database: %s", settings.DB_FILE)
        os.remove(settings.DB_FILE)

    # Skip creation if DB already exists
    if os.path.exists(settings.DB_FILE):
        logger.info("Database already exists. Nothing to do.")
        return

    logger.info("Creating database: %s", settings.DB_FILE)

    # Ensure directory exists
    os.makedirs(os.path.dirname(settings.DB_FILE) or ".", exist_ok=True)

    # Initialize DB tables
    init_db()

# ------------------------------------------------------------------------------
# Bootstrap: setup logging, print welcome, create DB, etc.
# ------------------------------------------------------------------------------
def bootstrap():

    # Log Setup
    setup_logging(level=settings.LOG_LEVEL, to_file=settings.LOG_TO_FILE, log_file=settings.LOG_FILE, log_access_file=settings.LOG_ACCESS_FILE)
    logger = get_logger(__name__)

    print_welcome(logger)

    # Create or update database
    docker_create_db(logger)

    #os.makedirs(DATA_DIR, exist_ok=True)
    #os.makedirs(BIND_DIR, exist_ok=True)
    #os.makedirs(KEA_DIR, exist_ok=True)

    #if not os.path.exists(DB_PATH):
    #    conn = sqlite3.connect(DB_PATH)
    #    # eventuale executescript(schema) qui
    #    conn.close()

    #named_conf = os.path.join(BIND_DIR, "named.conf")
    #if not os.path.exists(named_conf):
    #    with open(named_conf, "w") as f:
    #        f.write("// generated by network-manager\n")

    #kea_conf = os.path.join(KEA_DIR, "kea-dhcp4.conf")
    #if not os.path.exists(kea_conf):
    #    with open(kea_conf, "w") as f:
    #        f.write("{\n  // generated by network-manager\n}\n")
